spring:
  application:
    name: taco-cloud
  main:
    banner-mode: off
  datasource:
    name: tacocloud
    generate-unique-name: false


    #????????? ??????????? ????????. ?????? ??? ??????????
    #spring.thymeleaf.cache=false
    #?????? ??? ??? ???? ?????? H2